# Generated by Django 4.2.7 on 2024-02-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_visit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
