# Generated by Django 4.2.7 on 2024-03-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_last_name_user_lastname'),
    ]

    operations = [
    ]
