# Generated by Django 4.2.7 on 2024-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.CharField(default=1, max_length=100, verbose_name='Товары'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
    ]
